optim: adam
max_epoch: 30
batch_type: folded
batch_size: 1024 # 300 for word LMs
lm: transformer
lm_conf:
    pos_enc: null
    embed_unit: 128
    att_unit: 512
    head: 8
    unit: 2048
    layer: 16
    dropout_rate: 0.1
val_scheduler_criterion:
-    - valid
     - loss
early_stopping_criterion:
-    - valid
     - loss
     - min
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10
grad_clip: 5.0
grad_clip_type: 2.0
